### ISSUE TITLE
Missing shared libraries when loading pre-signed S3 URL

### ISSUE THREAD

**Issue by trevorharwell** [phishy/mediainfo-lambda#1]
I first want to extend my deepest thanks to you for creating this project.  I literally spent an entire day trying to figure out how to get mediainfo to run in aws lambda.  So this project got me 90% of the way there.

What I found was that adding `libcurl.so.4` was not enough when I tried to have mediainfo load .a url that I pre-signed with the aws-sdk.  I got an error saying it couldn't find libnghttp2.so.14.  If you run `ldd libcurl.so.4` you can see that there are bunch of shared libraries that it needs that don't exist in the aws lambda environment.  This is actually confusing to me since the docker `amazonlinux:2` image does in fact have all the required libraries but I verified that a lambda runtime (using node10.x) does not have them.   I had to add the following to the list of included libs:

- libcrypt.so.1
- libidn2.so.0
- liblber-2.4.so.2
- libldap-2.4.so.2
- libnghttp2.so.14
- libnss3.so
- libnssutil3.so
- libsasl2.so.3
- libsmime3.so
- libssh2.so.1
- libssl3.so
- libunistring.so.0

Additionally, I had to change the load order in the `LD_LIBRARY_PATH` environment variable such that the lambda task lib folder takes precedence over the system lib folder.

I don't know if anyone else had this problem but I thought I would at least mention it here so someone doesn't have to go through all the pain that I did!

**Comment by phishy** [comment]
Sorry for the late reply on this. This is awesome, thank you! I'm glad you got it worked out!
